set_property PACKAGE_PIN AA38 [get_ports XCLKP]
set_property PACKAGE_PIN AA39 [get_ports XCLKN]
set_property IOSTANDARD LVDS [get_ports XCLKP]
set_property IOSTANDARD LVDS [get_ports XCLKN]

set_property PACKAGE_PIN AP31 [get_ports XRES]
set_property IOSTANDARD LVCMOS18 [get_ports XRES]

set_property PACKAGE_PIN BA34 [get_ports UART_RXD]
set_property IOSTANDARD LVCMOS18 [get_ports UART_RXD]
set_property PACKAGE_PIN AV39 [get_ports UART_TXD]
set_property IOSTANDARD LVCMOS18 [get_ports UART_TXD]

set_property PACKAGE_PIN AP39 [get_ports DEBUG[0]]
set_property IOSTANDARD LVCMOS18 [get_ports DEBUG[0]]
set_property PACKAGE_PIN AR37 [get_ports DEBUG[1]]
set_property IOSTANDARD LVCMOS18 [get_ports DEBUG[1]]
set_property PACKAGE_PIN AP38 [get_ports DEBUG[2]]
set_property IOSTANDARD LVCMOS18 [get_ports DEBUG[2]]
set_property PACKAGE_PIN AP40 [get_ports DEBUG[3]]
set_property IOSTANDARD LVCMOS18 [get_ports DEBUG[3]]

set_property PACKAGE_PIN AN39 [get_ports LED[0]]
set_property IOSTANDARD LVCMOS18 [get_ports LED[0]]
set_property PACKAGE_PIN AP44 [get_ports LED[1]]
set_property IOSTANDARD LVCMOS18 [get_ports LED[1]]
set_property PACKAGE_PIN AP43 [get_ports LED[2]]
set_property IOSTANDARD LVCMOS18 [get_ports LED[2]]
set_property PACKAGE_PIN AN44 [get_ports LED[3]]
set_property IOSTANDARD LVCMOS18 [get_ports LED[3]]
